
    create table Parameter (
       id bigint generated by default as identity,
        name varchar(255),
        sourceType varchar(255),
        primary key (id)
    );

    create table PhishingTarget (
       id bigint generated by default as identity,
        createdAt timestamp not null,
        emailAddress varchar(255) not null,
        lastModified timestamp not null,
        primary key (id)
    );

    create table PhishingTargetParameter (
       id bigint generated by default as identity,
        value varchar(255) not null,
        entity bigint,
        parameter bigint,
        primary key (id)
    );

    alter table Parameter 
       add constraint uk_name_sourceType unique (name, sourceType);

    alter table PhishingTarget 
       add constraint UK_t31vfpaimg746lpygo9y08jkc unique (emailAddress);

    alter table PhishingTargetParameter 
       add constraint UK9f7o0sv9svix45arcw4q2b40q unique (entity, parameter);

    alter table PhishingTargetParameter 
       add constraint FK89gj4k8b4tuj7y7x1ppgmiy5b 
       foreign key (entity) 
       references PhishingTarget;

    alter table PhishingTargetParameter 
       add constraint FKayppg5mc5qasc87nxk1gphgfj 
       foreign key (parameter) 
       references Parameter;
