
    create table EmailTemplate (
       id bigint generated by default as identity,
        created_at timestamp not null,
        last_Modified timestamp not null,
        name varchar(255) not null,
        originalHtml varchar(1000000) not null,
        sourceHtml varchar(1000000) not null,
        primary key (id)
    );

    create table EmailTemplate_SpoofTarget (
       template_id bigint not null,
        spoof_id bigint not null
    );

    create table Parameter (
       id bigint generated by default as identity,
        name varchar(255),
        sourceType varchar(255),
        primary key (id)
    );

    create table PhishingTarget (
       id bigint generated by default as identity,
        createdAt timestamp not null,
        emailAddress varchar(255) not null,
        lastModified timestamp not null,
        primary key (id)
    );

    create table PhishingTargetParameter (
       id bigint generated by default as identity,
        value varchar(255) not null,
        entity bigint,
        parameter bigint,
        primary key (id)
    );

    create table Sender (
       id bigint generated by default as identity,
        created_at timestamp not null,
        last_Modified timestamp not null,
        loginName varchar(255) not null,
        password varchar(255) not null,
        server_id bigint not null,
        primary key (id)
    );

    create table SenderServer (
       id bigint generated by default as identity,
        created_at timestamp not null,
        last_Modified timestamp not null,
        name varchar(255) not null,
        host varchar(255) not null,
        port integer not null,
        tls boolean not null,
        primary key (id)
    );

    create table SpoofTarget (
       id bigint generated by default as identity,
        createdAt timestamp not null,
        emailAddress varchar(255) not null,
        lastModified timestamp not null,
        primary key (id)
    );

    create table SpoofTargetParameter (
       id bigint generated by default as identity,
        value varchar(255) not null,
        entity bigint,
        parameter bigint,
        primary key (id)
    );

    alter table EmailTemplate 
       add constraint UK_r9g3va2463hbkq4cglmjjmjxo unique (name);

    alter table Parameter 
       add constraint uk_name_sourceType unique (name, sourceType);

    alter table PhishingTarget 
       add constraint UK_t31vfpaimg746lpygo9y08jkc unique (emailAddress);

    alter table PhishingTargetParameter 
       add constraint UK9f7o0sv9svix45arcw4q2b40q unique (entity, parameter);

    alter table SenderServer 
       add constraint UK_jbwjjl7guqmim2n6c8cot7d61 unique (name);

    alter table SpoofTarget 
       add constraint UK_843v7n5rjcpoturo37kplm6ai unique (emailAddress);

    alter table SpoofTargetParameter 
       add constraint UKhk1y7bf2ya12sjnojisr321m5 unique (entity, parameter);

    alter table EmailTemplate_SpoofTarget 
       add constraint FKabifw8vjkk0xjfhumruugt1of 
       foreign key (spoof_id) 
       references SpoofTarget;

    alter table EmailTemplate_SpoofTarget 
       add constraint FKcyetgmsmyle46k5dvdai0oshc 
       foreign key (template_id) 
       references EmailTemplate;

    alter table PhishingTargetParameter 
       add constraint FK89gj4k8b4tuj7y7x1ppgmiy5b 
       foreign key (entity) 
       references PhishingTarget;

    alter table PhishingTargetParameter 
       add constraint FKayppg5mc5qasc87nxk1gphgfj 
       foreign key (parameter) 
       references Parameter;

    alter table Sender 
       add constraint FKn792mqtwofbcxeq253tjylew2 
       foreign key (server_id) 
       references SenderServer;

    alter table SpoofTargetParameter 
       add constraint FK33y46d3xp7l91n44lgj0shnqb 
       foreign key (entity) 
       references SpoofTarget;

    alter table SpoofTargetParameter 
       add constraint FKglxjnkbprgh167lp84sflk57d 
       foreign key (parameter) 
       references Parameter;
