
    create table EmailTemplate (
       id bigint generated by default as identity,
        timeAdded timestamp not null,
        name varchar(255) not null,
        originalHtml varchar(10000) not null,
        sourceHtml varchar(10000) not null,
        primary key (id)
    );

    create table EmailTemplate_SpoofTarget (
       template_id bigint not null,
        spoof_id bigint not null
    );

    create table PhishingTarget (
       id bigint generated by default as identity,
        timeAdded timestamp not null,
        EmailAddress varchar(255) not null,
        primary key (id)
    );

    create table Sender (
       id bigint generated by default as identity,
        timeAdded timestamp not null,
        loginName varchar(255) not null,
        password varchar(255) not null,
        server_id bigint not null,
        primary key (id)
    );

    create table SenderServer (
       id bigint generated by default as identity,
        timeAdded timestamp not null,
        name varchar(255) not null,
        host varchar(255) not null,
        port integer not null,
        tls boolean not null,
        primary key (id)
    );

    create table SpoofTarget (
       id bigint generated by default as identity,
        timeAdded timestamp not null,
        EmailAddress varchar(255) not null,
        primary key (id)
    );

    alter table EmailTemplate 
       add constraint UK_r9g3va2463hbkq4cglmjjmjxo unique (name);

    alter table PhishingTarget 
       add constraint UK_gx2psqnqcrcxu94ee140l8lrx unique (EmailAddress);

    alter table SenderServer 
       add constraint UK_jbwjjl7guqmim2n6c8cot7d61 unique (name);

    alter table SpoofTarget 
       add constraint UK_h3ix1o4g9mam91489pp21i3h9 unique (EmailAddress);

    alter table EmailTemplate_SpoofTarget 
       add constraint FKabifw8vjkk0xjfhumruugt1of 
       foreign key (spoof_id) 
       references SpoofTarget;

    alter table EmailTemplate_SpoofTarget 
       add constraint FKcyetgmsmyle46k5dvdai0oshc 
       foreign key (template_id) 
       references EmailTemplate;

    alter table Sender 
       add constraint FKn792mqtwofbcxeq253tjylew2 
       foreign key (server_id) 
       references SenderServer;
