//make sure to add the spoofTarget good@gmail.com before running this request
POST localhost:8080/api/emailTemplate/add
Host: localhost:8080
Content-Type:application/json

{
    "name" : "template",
    "sourceHtml" : "Hi jack, My name is Joe",
    "originalHtml": "original Html"
}

###