:table-caption!:

== add

=== Info
[cols="2*"]
|====

|Type
|POST

|Url
|/api/phishingTarget/add


|Description
|adds the phishing target specified by the json in the request body to the database.
|====

=== Request

[cols="3*"]
|===

|Content Type
2+|application/json

|Note
2+|
Id, createdAt, lastModified are not required and will be ignored if included.

|emailAddress
2+| this field is required and an error will be thrown if its missing.

|parameterList
2+| this field is optional.
|===
.Request json
[source]
{
    emailAddress: emailAddress,
    parameterList:
    {
        parameterName: parameterValue,
        ...
    }
}



=== Response

==== Missing Email Address Response
.Info
[cols="3*"]
|====

|Condition
2+|When the request body json does not contain an emailAddress field.

|Code
2+|400 BAD REQUEST
|====
.Response Json
[source]
{
    error: "Missing required emailAddress field in the json"
}

==== Email Already Exist Response
.Info
[cols="3*"]
|====
|Condition
2+|when a phishing Target with the same email address already exist on the server.

|Code
2+|BAD 400
|====

.Response Json
[source]
{
    error: "A phishing Target with the same email address already exists on the server"
}

==== Successful Response
.Info
[cols="3*"]
|====
|Condition
2+| When the request is valid and executed successfully

|code
2+|OK 200

|Description
2+|
Returns the following fields: id, lastModified, and createdAt
|====


.Response Json
[source]
{
    id:number,
    lastModified: time,
    createdAt: time
}